#OOPS 
# OBJECT ORIENTED PROGRAMMING STRUCTURE
# REPRESENTATION OF REAL WORLD ENTITIES IN THE PROGRAMMING WORLD


# CLASS - BLUEPRINT OF THE OBJECT
# CLASS MEANS A BLUEPRINT OR TEMPLATE FOR CREATING OBJECTS
# IT DEFINES THE PROPERTIES AND BEHAVIOR OF THE OBJECTS
# EXAMPLE - CAR, STUDENT, EMPLOYEE, BANK ACCOUNT
# IT IS A BLUEPRINT/TEMPLATE/DESIGN FOR CREATING SIMILAR OBJECTS

# IT IS A DATATYPE IN PYTHON LIKE INT, FLOAT, STRING
# IT IS A USER DEFINED DATATYPE



#==============================================================================
# EXECUTABLE CODE STARTS FROM HERE


# SIMILAR TO A BLUEPRINT OF A HOUSE, IT DEFINES THE STRUCTURE AND LAYOUT OF THE HOUSE BUT DOES NOT REPRESENT THE ACTUAL HOUSE
# THESE IS INSTANCE OF THE CLASS - OBJECTS

# OBJECT - INSTANCE OF THE CLASS
# ANY REAL WORLD ENTITY(PHYSICAL/LOGICAL)WITH DATA AND FUNCTIONS

#IT IS AN INSTANCE OF A CLASS
# INSTANCE MEANS EXCISTENCE OF THE COPY OF THE CLASS
# BACCHA CLASS - BLUEPRINT OF THE OBJECT
# EXAMPLE - CAR, STUDENT, EMPLOYEE, BANK ACCOUNT

# EXAMAPLE 1- CAR, STUDENT, EMPLOYEE, BANK ACCOUNT
# IF MOBILE IS AND OBJECT 
#DATA - COLOR, MODEL, PRICE
#FUNCTIONS - CALL, MESSAGE, CAMERA, GAMES

#EXAMPLE 2 -BANK ACCOUNT
#BANK ACCOUNT AS A OBJECT
#DATA - ACCOUNT NUMBER, ACCOUNT HOLDER NAME, BALANCE
#FUNCTIONS - DEPOSIT, WITHDRAW, CHECK BALANCE

#EXAMPLE 3 - STUDENT
#HUMAN AS AN OBJECT
#DATA - NAME, AGE, G        
#FUNCTIONS - EAT, SLEEP, WORK, STUDY


#==============================================================================











#ENCAPSULATION - BINDING DATA AND METHODS TOGETHER
#INHERITANCE - DERIVING NEW CLASSES FROM EXISTING CLASSES
#POLYMORPHISM - ABILITY OF AN OBJECT TO TAKE MANY FORMS
#ABSTRACTION - HIDING INTERNAL DETAILS AND SHOWING ONLY ESSENTIAL FEATURES