#1. Write a Python program to print the following string in a specific format (see the output). 

print ("TWINKLE, twinkle, little star,")
print ("\t How I wonder what you are!")
print ("\t\t Up above the world so high,")
print ("\t\t Like a diamond in the sky.")
print ("TWINKLE, twinkle, little star,")
print ("\t How I wonder what you are")


#or we can just copy paste with multi-line string '''


print('''TWINKLE, twinkle, little star,
         How I wonder what you are!
                 Up above the world so high,
                 Like a diamond in the sky.
TWINKLE, twinkle, little star,
         How I wonder what you are''')

#2. WAP to print names of your 5 friends each in new line using single print() and single string.

print (" Bharti\nKairoo\n lailaa\n Munni\n YUm")
print('''  Bharti
Kairoo
 lailaa
 Munni
 YUm ''')

#3. WAP to print names of your 5 friends each in new line using single print() and independent string for each name.

print ("BHarti",  "Kairoo", "lailaa", "Munni", "YUM", sep= "\n")

#4. WAP to print names of your 5 friends each in new line using 5 print().

print("Bharti")
print ("Kairoo")
print ("lailaa")
print ("Munni")
print ("Yum")

#5.  WAP to print \t and \n as it is in the output.

print("bharti\\n moon\\t")
print(r'\n\t')


