'''1. Find area of circle'''

PI = 3.14
r = 5
area = PI * r**2
print(area)


'''
2. Find area of rectangle'''

l= 10
b= 5
area = l * b
print(area)



'''

3. Find square of a number'''

n= 10
square = n**2
print(square)


'''
4. convert dollar value to INR'''

dollar = 100
exchange_rate = 82.5
INR = dollar * exchange_rate
print(INR)

'''
5. calculate simple interest'''

P = 1000
R = 5
T = 2
SI = (P * R * T) / 100
print(SI)

'''
Note: You may consider your own values to solve above
questions'''